### ISSUE TITLE
Binary `swift` REPL fails to start.

### ISSUE THREAD

**Issue by tildebyte** [tinysun212/swift-cygwin-bin#1]
Latest cygwin-64 (as of 2016-02-01), Windows 7 Enterprise x64 SP1.
`LLVM ERROR: Compiler-internal integrated REPL unimplemented for this platform; use the LLDB-enhanced REPL instead.`

**Comment by tildebyte** [comment]
P.S. also with hand-built binaries.

**Comment by tinysun212** [comment]
The standard library can be used and It is possible to compile and run or interpret a simple hello swift source, but REPL, swift-build and swift-lldb does not work.
Currently, build process is not good, and many bugs may exist in.
You can use this as follows.
  ./swift  Hello.swift
OR 
  ./swiftc Hello.swift
  ./Hello

**Comment by tildebyte** [comment]
OK, I figured that that was probably the case.
