### ISSUE TITLE
Build instructions: `Unknown operating system`. 

### ISSUE THREAD

**Issue by tildebyte** [tinysun212/swift-cygwin-bin#3]
Latest cygwin-64 (as of 2016-02-01), Windows 7 Enterprise x64 SP1.
~~Trying to work around #2 using `utils/build-script -m -R` (force use of `make`),~~ (_edit_: seems unrelated to build system in use) I run into
`Unknown operating system`
which seems to originate from `swift/utils/build-script-impl`.
Replacing `CYGWIN_NT-10.1\ x86_64` with `CYGWIN_NT-6.1\ x86_64` (the actual output of `uname -s -m` on my system) gets me past it.
I'd submit a patch, but I don't know the ramifications of this change outside of merely getting the build underway.

**Comment by tinysun212** [comment]
I think It would only affect to building process.

**Comment by tildebyte** [comment]
Sure, but good to document that there may be differences based on Cygwin/Windows version.
